// app/layout.tsx
import type { Metadata } from "next";
import "./styles/globals.scss";
import "./styles/roots.scss";
import SessionProviderClient from "@/app/SessionProviderClient";
import { Navbar } from "@/app/components/navbar/page";

export const metadata: Metadata = {
  title: "Avenue Mondaine",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fr">
      <body>
        {/* Pour la session utilisateur */}
        <SessionProviderClient>
          <Navbar />
          {children}
        </SessionProviderClient>
      </body>
    </html>
  );
}
